# Generated by Django 4.2.5 on 2023-10-26 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
